In [498]:
import sklearn # make sure this is installed in your environment.
from sklearn.datasets import *
from sklearn import tree
from sklearn.preprocessing import OneHotEncoder
from numpy import array
import numpy as np
import pandas as pd
import csv
import random
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [ ]:
"""
This homework assumes that you have completed hw-1 and are familiar 'enough' with Python by now. Our main goal
in this homework is to play with sklearn, which is the primary toolkit in Python that is used for basic machine
learning like the models we studied in class (Naive Bayes, decision trees, linear classifiers and regressors).

For our experiments, we will use a dataset publicly available in the UCI repository, namely the Bank Marketing Data Set.
While this is not a 'text' dataset, as we studied in class, the classification models/supervised learning tend to involve the same
kinds of workflow. This dataset is easier to work with than a text dataset because of the presence of numeric attributes (not requiring
you to really know 'vector space models' in detail).

Go to the website to read more: https://archive.ics.uci.edu/ml/datasets/Bank+Marketing
All files mentioned/referenced below can be found at this link.

Note that we will be using the bank-additional-full.csv file for our experiments. This is the most complete
dataset (i.e. has all 41,000+ examples and 20 attributes). It is a binary classification task (the very last column,
which is either a yes or a no). However, as you'll see, even before we can get to all the good model fitting
stuff, there's some data cleaning/processing that we'll need to do first.

In python we often use 'pass' as a placeholder. Wherever you see 'pass', it's a sign that you should replace with
your own code (which could span multiple lines).

If it makes you comfortable to define additional functions or data structures to help you, go for it.

Do not forget to 'call' the functions as necessary, as you proceed with the assignment.

HINT: The first part of this exercise (in my opinion) is the most time-consuming, despite technically being
the easiest, just like in actual analytics projects (in practice, about 80-90% time
in machine learning/data science projects in the real-world are taken up by 'data cleaning/wrangling'). I realize
 that you may want to work on some of the other stuff before being able to parse the file into a matrix. One piece of
 advice is that many of the other function rely on generic matrices X and y, which you can get from sklearn's
 sample datasets. I'll provide some guidance below. The important thing to remember is, you can  'test' the functions
 out of order, although to complete the assignment you will need to finish everything I ask you below.

 Perhaps a shorter way to state the hint above is, read the entire assignment before jumping on to it, and be
 strategic about how you allocate time to the various problems. Don't get frustrated!

 (Another) HINT: Make sure you have imported everything you need at the top of this file!

 Total possible points are 100.

Good luck!
"""

# [30 points] Complete encode_record_into_vector and parse_file_into_matrix

In [ ]:
 """
    the goal of this function is to take a record (informally, a 'row' in your file)
    and 'encode' it numerically so that we can actually do
    machine learning with it. How you do the encoding is up to you, but one recommended way is to:
    --leave the numeric variables (like age) as is
    --assign a 'one hot encoding' to each possible value of a `categorical' variable. For example, for the categorical
    variable 'loan', we have three possible values ('no', 'yes', 'unknown'). Since there are three possible values,
    you can do a 'one hot encoding' by using three binary 'variables'. We may want to assign 'no' to 0 0 1,
    'yes' to 0 1 0  and 'unknown' to 1 0 0 (you can see now why it's called one hot encoding).
    :param record: I highly recommend that record be a 'dict', but you can use other data structures (like 'list') if
    you want. For example,
    you could even just pass in a string! However, the output MUST be a numeric vector.
    Also, we will not do 'type' checking on this function, so you don't need to waste time checking for exceptions,
    or worrying that we will try to trip you up by running your code using weird inputs.
    The only requirement is that code you write must work for the dataset used in this assignment.
    :return:
    x: the vector representation of the record

    """

In [463]:
def encode_record_into_vector(record):
    
    def job_helper(x):
        job = OneHotEncoder()
        l=array(['admin.','blue-collar','entrepreneur','housemaid','management',
             'retired','self-employed','services','student','technician'
             ,'unemployed','unknown']).reshape(-1, 1) 
        job.fit(l)
        X_encod = job.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod.tolist()

    def marital_helper(x):
        marital = OneHotEncoder()
        l=array(['divorced','married','single', 'unknown']).reshape(-1, 1) 
        marital.fit(l)
        X_encod = marital.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod

    def education_helper(x):
        education = OneHotEncoder()
        l=array(["basic.4y","basic.6y","basic.9y",
                 "high.school","illiterate","professional.course",
                 "university.degree","unknown"]).reshape(-1, 1) 
        education.fit(l)
        X_encod = education.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod
        
    def default_helper(x):
        default = OneHotEncoder()
        l=array(['no','yes','unknown']).reshape(-1, 1) 
        default.fit(l)
        X_encod = default.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod    
    
    def housing_helper(x):
        housing = OneHotEncoder()
        l=array(['no','yes', 'unknown']).reshape(-1, 1) 
        housing.fit(l)
        X_encod = housing.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod
    
    def loan_helper(x):
        loan = OneHotEncoder()
        l=array(['no','yes','unknown']).reshape(-1, 1) 
        loan.fit(l)
        X_encod = loan.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod
    
    def contact_helper(x):
        contact = OneHotEncoder()
        l=array(['cellular','telephone']).reshape(-1, 1) 
        contact.fit(l)
        X_encod = contact.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod
    
    def month_helper(x):
        month = OneHotEncoder()
        l=array([ 'jan', 'feb', 'mar','apr','may','jun','jul','aug','sep','oct', 'nov', 'dec']).reshape(-1, 1) 
        month.fit(l)
        X_encod = month.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod
    
    def day_of_week_helper(x):
        day_of_week = OneHotEncoder()
        l=array([ 'mon','tue','wed','thu','fri']).reshape(-1, 1) 
        day_of_week.fit(l)
        X_encod = day_of_week.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod
    
    def poutcome_helper(x):
        poutcome = OneHotEncoder()
        l=array([ "failure","nonexistent","success"]).reshape(-1, 1) 
        poutcome.fit(l)
        X_encod = poutcome.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod
    
    def y_helper(x):
        y = OneHotEncoder()
        l=array([ 'yes','no']).reshape(-1, 1) 
        y.fit(l)
        X_encod = y.transform(array([x]).reshape(-1, 1)).toarray()
        return X_encod
    
    x=array([])
    x=np.append(x,record['age'])
    x=np.append(x,job_helper(record['job']))
    x=np.append(x,marital_helper(record['marital']))
    x=np.append(x,education_helper(record['education']))
    x=np.append(x,default_helper(record['default']))
    x=np.append(x,housing_helper(record['housing']))
    x=np.append(x,loan_helper(record['loan']))
    x=np.append(x,contact_helper(record['contact']))
    x=np.append(x,day_of_week_helper(record['day_of_week']))
    x=np.append(x,month_helper(record['month']))
    x=np.append(x,record['duration'])
    x=np.append(x,record['campaign'])
    x=np.append(x,record['pdays'])
    x=np.append(x,record['previous'])
    x=np.append(x,poutcome_helper(record['poutcome']))
    x=np.append(x,record['emp.var.rate'])
    x=np.append(x,record['cons.price.idx'])
    x=np.append(x,record['cons.conf.idx'])
    x=np.append(x,record['euribor3m'])
    x=np.append(x,record['nr.employed'])
    x=np.append(x,y_helper(record['y']))
    
    #pass  Hint: use helper functions to encode categorical variables as vectors that can be appended to the (bigger) x vector
    # rather than write a lot of messy code here. It will also help you to try more things.
    return x

In [464]:
#Example
record=dict()
record['age']=58
record['job']='management'
record['marital']='married'
record['education']='basic.4y'
record['default']='no'
record['housing']='yes'
record['loan']='no'
record['contact']='cellular'
record['day_of_week']='thu'
record['month']='may'
record['duration']=261
record['campaign']=1
record['pdays']=-1
record['previous']=0
record['poutcome']='nonexistent'
record['emp.var.rate']=1.1
record['cons.price.idx']=93.994
record['cons.conf.idx']=-36.4
record['euribor3m']=4.857
record['nr.employed']=5191
record['y']='yes'

In [465]:
encode_record_into_vector(record)

array([ 5.8000e+01,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        1.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,
        0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        1.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        1.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  2.6100e+02,  1.0000e+00,
       -1.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
        1.1000e+00,  9.3994e+01, -3.6400e+01,  4.8570e+00,  5.1910e+03,
        0.0000e+00,  1.0000e+00])

In [ ]:
    """
    Hint 1: Even though the file is a .csv, be careful about using Python's csv package for reading in the file.
    The single biggest source of error is not reading in the file correctly. It's good to test that you're
    doing the initial data processing correctly on the first few records.

    Hint 2: This function will make a call to encode_record_ for each record (not including header) in your input file
    :param file_name: The path to the bank-additional-full.csv file
    :return:
    X: A D X p matrix, where D is the number of 'instances' or records in the file and p is the dimensionality of
    the x vector that is output by the previous function. I won't give you the value for p; you have to know what it is
    based on your code in encode_record_into_vector
    y: A D X 1 matrix containing only 1's (for 'yes' in the output variable) or 0's (for 'no')
    """

In [467]:
def parse_file_into_matrix(file_name):
    X=[]
    y=[]
    with open(file_name, mode='r') as infile:
        reader=csv.reader(infile)
        header=next(reader)
        if header != None:
            for row in reader:
                x = row[0].split(";")
                record=dict()
                record['age']=int(x[0])
                record['job']=x[1][1:-1]
                record['marital']=x[2][1:-1]
                record['education']=x[3][1:-1]
                record['default']=x[4][1:-1]
                record['housing']=x[5][1:-1]
                record['loan']=x[6][1:-1]
                record['contact']=x[7][1:-1]
                record['month']=x[8][1:-1]
                record['day_of_week']=x[9][1:-1]
                record['duration']=int(x[10])
                record['campaign']=int(x[11])
                record['pdays']=int(x[12])
                record['previous']=int(x[13])
                record['poutcome']=x[14][1:-1]
                record['emp.var.rate']=float(x[15])
                record['cons.price.idx']=float(x[16])
                record['cons.conf.idx']=float(x[17])
                record['euribor3m']=float(x[18])
                record['nr.employed']=float(x[19])
                record['y']=x[20][1:-1]
                temp1=encode_record_into_vector(record).tolist()
                X.append(temp1)
                if record['y']=='yes':
                    y.append(1)
                else:
                    y.append(0)

    return (X, y)

In [ ]:

"""
We will define 'positive' instances as those with label 1, and negative instances as those with label 0.

Q1 [5 points]. Write some code to count the number of 1s and 0s in y. How many positive and negative instances each
are in your dataset?
ANS:4640 1s and 36548 0s

"""

In [277]:
y.count(1)

4640

In [278]:
y.count(0)

36548

In [223]:
"""
If you want to do the next part before the previous part, I recommend calling X_y_for_running_tests below,
which reads in a sample dataset from sklearn. I've included a short snippet of code below for your reference. Remember, however, that
to score points, you must work with the banking dataset in the output you submit.
"""

def X_y_for_running_tests():
    # just call this, and it will return X and y.
    X, y = load_digits(2, True) # return only two classes, although there are ten total
    return X, y


In [225]:
X, y=X_y_for_running_tests()
print (X)
print ('now printing y')
print (y)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  1. ...  3.  0.  0.]
 ...
 [ 0.  0.  5. ...  8.  1.  0.]
 [ 0.  0.  6. ...  4.  0.  0.]
 [ 0.  0.  6. ...  6.  0.  0.]]
now printing y
[0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0
 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1
 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0
 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0
 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 0 1
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0
 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1
 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0
 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1
 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0]


In [ ]:
    """
    Here's an opportunity to test your sampling skills  using numpy. We want to do stratified sampling on X, y. Basically,
     this means that we want to 'split' the original X, y (the 'complete' dataset) into a training dataset (X_train, y_train)
     that will be used for training the model, and a testing dataset (X_test, y_test) that will be used for evaluating
     the model. Here are the requirements:
     --Since the sampling is stratified, we want to make sure that the proportion of positive instances (to total instances)
     is equal in both training and testing data. For example:
        Imagine that you had 100 positive instances and 50 negative instances in your full dataset. Suppose the training_Ratio
        is 80%, as specified by default in the signature. Then, we want to randomly sample 0.8*100 positive instances (or 80
        instances) and 0.8*50 negative instances (or 40 instances) and place all 120 instances in X_train (correspondingly, y_train
        is filled with 1s and 0s based on the label). The remaining 30 instances (20 positive and 10 negative) are
        placed in X_test (with y_test populated with 1s and 0s correspondingly). Notice that the ratio of positive
        to positive+negative is equal in both training and testing datasets (compute it for yourself), and by extension,
        so is the ratio of negative to positive+negative. There is a very good reason why this is so important (recall
        the definition of learning in our very first slide! Would the test data still be from the same population as the
        training data if we did not decide to 'stratify' the sample in this way?)
     --Your method should work for any numeric choice of X, y and training ratio (that is between 0 and 1, including the extreme
     cases of 0 and 1). We may test this function with X, y and training_ratio values of our own!
    """

In [478]:
def training_testing_split(X, y, training_ratio):
    X_train, y_train, X_test, y_test=[],[],[],[]
    X_1, X_0=[],[]
    for i in X:
        if (i[-1]==1) & (i[-2]==0):
            X_1.append(i[:-2])
        else:
            X_0.append(i[:-2])
    list1=random.sample(range(len(X_1)),int(len(X_1)*training_ratio))
    list0=random.sample(range(len(X_0)),int(len(X_0)*training_ratio))
    for p in range(len(X_1)):
        if p in list1:
            X_train.append(X_1[p])
            y_train.append(1)
        else:
            X_test.append(X_1[p])
            y_test.append(1)
    for q in range(len(X_0)):
        if q in list0:
            X_train.append(X_0[q])
            y_train.append(0)
        else:
            X_test.append(X_0[q])
            y_test.append(0)
    pass
    return (X_train, y_train, X_test, y_test)

In [305]:
"""
Q2 (20 points). Run the code above with the X and y that you got from parse_file_into_matrix, with training ratios
of 0.8, 0.5, 0.3 and 0.1. For each of these four cases, what is the 'ratio' of positive instances in the training
dataset to the total number of instances in the training dataset? Verify that this same ratio is achieved in the test
dataset. Write additional code to run these verifications if necessary (5 points per case).
"""

In [ ]:
# 0.8

In [311]:
X_train, y_train, X_test, y_test=training_testing_split(X, y, 0.8)

In [336]:
y_train.count(1)/len(y_train)

0.11265553869499241

In [337]:
y_test.count(1)/len(y_test)

0.11264870114105366

In [317]:
# 0.5

In [329]:
X_train1, y_train1, X_test1, y_test1=training_testing_split(X, y, 0.5)

In [330]:
y_train1.count(1)/len(y_train1)

0.11265417111780131

In [335]:
y_test1.count(1)/len(y_test1)

0.11265417111780131

In [ ]:
# 0.3

In [340]:
X_train2, y_train2, X_test2, y_test2=training_testing_split(X, y, 0.3)

In [341]:
y_train2.count(1)/len(y_train2)

0.11265781806409841

In [342]:
y_test2.count(1)/len(y_test2)

0.11265260821309656

In [ ]:
# 0.1

In [346]:
X_train3, y_train3, X_test3, y_test3=training_testing_split(X, y, 0.1)

In [347]:
y_train3.count(1)/len(y_train3)

0.11267605633802817

In [348]:
y_test3.count(1)/len(y_test3)

0.11265173995144322

In [ ]:
    """
    In the code below, I have trained a model specifically for decision tree. You must expand the code to accommodate
    the other two models. To learn more about sklearn's decision trees, see https://scikit-learn.org/stable/modules/tree.html
    :param X_train: self-explanatory
    :param y_train:
    :param model: we will allow three values for model namely 'decision_tree', 'naive_bayes' and 'linear_SGD_classifier'
    (Hint: you must change the loss function in https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html
    to squared_loss to correctly implement the linear classifier. For the naive bayes, the appropriate model to use
    is the Bernoulli naive Bayes.)


    :return:
    """
    """
    [10 points] Expand/replace 'pass' above to return the other two models based on the value of the model parameter 'model' [10 points]
    [5 points] Expand to return one other model that I have not taught in class.
    """

In [499]:
def train_models(X_train,y_train,model):
    if model == 'decision_tree':
        clf = tree.DecisionTreeClassifier()
        clf = clf.fit(X_train, y_train)
        return clf
    if model == 'naive_bayes':
        clf=BernoulliNB()
        clf=clf.fit(X_train, y_train)
    if model == 'linear_SGD_classifier':
        clf = make_pipeline(StandardScaler(),SGDClassifier(loss="squared_loss"))
        clf=clf.fit(X_train, y_train)
    if model == 'gradient_tree_boosting':
        clf=GradientBoostingClassifier()
        clf=clf.fit(X_train, y_train)
    return clf

In [ ]:
    """
    Note that the model here is different from model in train_models. Here, we will be passing in the 'actual' trained
    model and using it to evaluate X_test and y_test

    We will be using the F_measure metric to evaluate the model: I have already written code in compute_f_measure
     that takes your predicted y, produced in this function, as well as the 'true' y, which is y_test, and will
     return a number to you within 0 and 1. The higher the f-measure, the better. I will briefly explain in class
     why we prefer f-measure over accuracy in many ML tasks.
    """

In [359]:
"""
Code for this function has already been written
"""
def evaluate_model(X_test, y_test, model):
    y_predict = model.predict(X_test)
    return sklearn.metrics.f1_score(y_test, y_predict)

In [ ]:
"""
[20 points] Compile a 5-table report with 10 rows per table. You must submit this report with your assignment submission
(any reasonable format is fine). Each table will correspond to a value of training percent, specifically 10%,30%,50%,70%,90%
Each table will contain four columns (trial number ranging from 1-10, decision_tree, naive_bayes and linear_classifier).
In each cell, you will be reporting the f-measure achieved. Completing this question will also require you to complete
the code for trials() below. trials() does NOT HAVE to (although it could) directly produce the table(s) but must give you all the information
you need, or write information out to file, that is needed for you to populate the tables.

Hint: It is okay to produce and print out intermediate outputs to file if necessary. For example, if you want
you could print out the 'encoded' version of the dataset (which only has numbers) to file, and just read that in
to save on time. Also, if there are some things that are constant, it is perfectly fine to define those constants
or fix variable values outside trials. As always, I want to be reasonable in evaluating these things; the goal is not
to trip you up or make you follow every instruction to the letter.

[15 points] Now we will return to some statistics (you can use whatever tool you want, or even do it manually!). You should
ignore the linear classifier for this question. Our null hypothesis is that the decision tree is better than naive bayes.
(or our alternate hypothesis is that the naive bayes is better than decision tree). For each of the five training percentages,
using 95% as the confidence level, can you reject the null hypothesis? State your p-values here for all five training
percentages. Which test did you use?



"""

In [506]:
def trials(file_name, training_ratio):
    """
    Think of this as the 'main' or master function from which you will be calling all other code. You must modify
    this code appropriately for your experiments (e.g., to vary training percentage, write out results to file etc.)
    I'm not giving you any hints or placeholders for this function; by now, you should be familiar with how to do
    what I've asked here!
    :return:
    """
    X, y=parse_file_into_matrix(file_name)
    data=dict()
    data['trial_number']=[1,2,3,4,5,6,7,8,9,10]
    l_dr,l_nb,l_lc=[],[],[]
    for i in range(10):
        X_train, y_train, X_test, y_test=training_testing_split(X, y, training_ratio)
        
        #decision tree
        clf=train_models(X_train,y_train,'decision_tree')
        l_nb.append(evaluate_model(X_test, y_test, clf))
        
        #dnaive_bayes
        clf=train_models(X_train,y_train,'naive_bayes')
        l_dr.append(evaluate_model(X_test, y_test, clf))
        
        #linear_classifier
        clf=train_models(X_train,y_train,'linear_SGD_classifier')
        l_lc.append(evaluate_model(X_test, y_test, clf))
     
    data['decision_tree']=l_dr
    data['naive_bayes']=l_nb
    data['linear_SGD_classifier']=l_lc
    
    df=pd.DataFrame (data, columns = ['trial_number','decision_tree','naive_bayes','linear_SGD_classifier'])
    return df

In [ ]:
10%,30%,50%,70%,90%

In [507]:
# 0.1 traing ratio
df1=trials('bank-additional-full.csv', 0.1)
df1

trial_number  decision_tree  naive_bayes  linear_SGD_classifier
0             1       0.380438     0.504333               0.175858
1             2       0.373743     0.510231               0.210546
2             3       0.373492     0.499882               0.177422
3             4       0.367047     0.488631               0.163442
4             5       0.369614     0.507393               0.140942
5             6       0.385105     0.515144               0.154673
6             7       0.385022     0.475478               0.180563
7             8       0.383674     0.504861               0.168085
8             9       0.370766     0.509497               0.207347
9            10       0.369381     0.485435               0.117835

In [508]:
# 0.3 traing ratio
df2=trials('bank-additional-full.csv', 0.3)
df2

/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarni

trial_number  decision_tree  naive_bayes  linear_SGD_classifier
0             1       0.384745     0.517777               0.174388
1             2       0.379644     0.505751               0.164932
2             3       0.373979     0.511036               0.182615
3             4       0.369402     0.513551               0.189139
4             5       0.376892     0.505017               0.156499
5             6       0.379395     0.507553               0.186499
6             7       0.377393     0.496450               0.251081
7             8       0.371248     0.513497               0.134763
8             9       0.364283     0.505772               0.153213
9            10       0.377830     0.514338               0.109481

In [509]:
# 0.5 traing ratio
df3=trials('bank-additional-full.csv', 0.5)
df3

/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarni

trial_number  decision_tree  naive_bayes  linear_SGD_classifier
0             1       0.372170     0.518363               0.208238
1             2       0.374292     0.506797               0.134276
2             3       0.369202     0.503196               0.207500
3             4       0.373671     0.508944               0.158737
4             5       0.377222     0.516520               0.183402
5             6       0.378190     0.512689               0.109070
6             7       0.376328     0.500324               0.204524
7             8       0.375812     0.508190               0.150877
8             9       0.369111     0.508330               0.136587
9            10       0.369030     0.509170               0.147007

In [510]:
# 0.7 traing ratio
df4=trials('bank-additional-full.csv', 0.7)
df4

/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarni

trial_number  decision_tree  naive_bayes  linear_SGD_classifier
0             1       0.389179     0.511644               0.149139
1             2       0.379809     0.540222               0.213370
2             3       0.373894     0.502146               0.170302
3             4       0.376963     0.491699               0.238138
4             5       0.376110     0.520489               0.142669
5             6       0.371676     0.517035               0.141257
6             7       0.359189     0.513250               0.434659
7             8       0.369136     0.503451               0.204580
8             9       0.362724     0.517528               0.139265
9            10       0.359620     0.515967               0.193335

In [511]:
# 0.9 traing ratio
df5=trials('bank-additional-full.csv', 0.9)
df5

/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/madison_w/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarni

trial_number  decision_tree  naive_bayes  linear_SGD_classifier
0             1       0.380952     0.531646               0.181893
1             2       0.368087     0.547718               0.170654
2             3       0.362117     0.519957               0.169647
3             4       0.363148     0.496774               0.217210
4             5       0.355917     0.503735               0.182909
5             6       0.380425     0.533762               0.201348
6             7       0.380866     0.480851               0.173913
7             8       0.333935     0.522560               0.147326
8             9       0.393352     0.517423               0.180655
9            10       0.353357     0.486545               0.180102

In [512]:
df1.to_csv('0.1.csv', index=False)
df2.to_csv('0.3.csv', index=False)
df3.to_csv('0.5.csv', index=False)
df4.to_csv('0.7.csv', index=False)
df5.to_csv('0.9.csv', index=False)